language: php
php:
  - 5.5.9
  - 5.3.3
  - 5.4
  - 5.5

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  ##PHPUnit
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils
  
before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
  ##php-cs-fixer
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
script:
  - cd app
  ##Usuario.php
  - php php-cs-fixer.phar fix Usuario.php
  - phpcs --standard=Zend Usuario.php
  - php phploc.phar Usuario.php
  ##functions.php
  - php php-cs-fixer.phar fix functions.php
  - phpcs --standard=Zend functions.php
  - php phploc.phar functions.php
  ##bienvenido.php
  - php-cs-fixer.phar fix bienvenido.php
  - phpcs --standard=Zend bienvenido.php
  - phploc.phar bienvenido.php
  ##crearcuenta.php
  - php-cs-fixer.phar fix crearcuenta.php
  - phpcs --standard=Zend crearcuenta.php
  - phploc.phar crearcuenta.php
  ##index.php
  - php-cs-fixer.phar fix index.php
  - phpcs --standard=Zend index.php
  - phploc.phar index.php

  - cd test
  ##Test.php
  - php-cs-fixer.phar fix Test.php
  - phpcs --standard=Zend Test.php
  - phploc.phar Test.php
  - phpunit Test.php
  - cd ..
  - phpunit --coverage-html . Test.php
 
 
  
