language: php
php:
  - 5.5.9
  - 5.3.3
  - 5.4
  - 5.5

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  ##PHPUnit
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils
  
before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  ## PHPLOC
  - pear install phpunit/phploc
  - phpenv rehash
  ##php-cs-fixer
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - chmod +x php-cs-fixer.phar

script:
  - php php-cs-fixer.phar fix app/Usuario.php
  - php php-cs-fixer.phar fix app/functions.php
  - php php-cs-fixer.phar fix app/index.php
  - php php-cs-fixer.phar fix app/bienvenido.php
  - php php-cs-fixer.phar fix app/crearcuenta.php
  
  - phpcs --standard=Zend app/Usuario.php
  - phpcs --standard=Zend app/functions.php
  - phpcs --standard=Zend app/index.php
  - phpcs --standard=Zend app/bienvenido.php
  - phpcs --standard=Zend app/crearcuenta.php
  
  - phploc app/Usuario.php
  - phploc app/functions.php
  - phploc app/index.php
  - phploc app/bienvenido.php
  - phploc app/crearcuenta.php
  
  - php-cs-fixer.phar fix  app/test/Test.php
  - phpcs --standard=Zend  app/test/Test.php
  - phploc app/test/Test.php
  - phpunit app/test/Test.php
  - phpunit --coverage-text . test/Test.php
  

  -phpunit app/test/pruebas_selenium/.
 
 
  
