language: php


# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils/
install:
  - sudo apt-get install php-codesniffer
  - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer
  - sudo chmod a+x php-cs-fixer
  - sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
script:
  - cd app
  - php-cs-fixer fix Usuario.php
  - phpcs --standard=Zend Usuario.php
  - php-cs-fixer fix functions.php
  - phpcs --standard=Zend functions.php
  - php-cs-fixer fix bienvenido.php
  - phpcs --standard=Zend bienvenido.php
  - php-cs-fixer fix crearcuenta.php
  - phpcs --standard=Zend crearcuenta.php
  - php-cs-fixer fix index.php
  - phpcs --standard=Zend index.php
  - cd test
  - php-cs-fixer fix test.php
  - phpcs --standard=Zend test.php
  - phpunit test.php
  - phpunit --coverage-html . test.php
 
 
  
