language: php
php:
  - 5.5.9

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  ##PHPUnit
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils
  
before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
 
  
 

script:
  - cd app/testCase
  - phpunit --version
  - phpunit --printer PHPUnit_Extensions_Story_ResultPrinter_Text testCaseActualizar.php
  - phpunit --printer PHPUnit_Extensions_Story_ResultPrinter_Text testCaseBorrar.php
  - phpunit --printer PHPUnit_Extensions_Story_ResultPrinter_Text testCaseBuscar.php
  - phpunit --printer PHPUnit_Extensions_Story_ResultPrinter_Text testCaseCrear.php
 
 
  
