language: php


# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils/

before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
script:
  - cd app
  - phpunit test.php
  - cd test
  - phpunit Test.php
  - phpunit --coverage-html . test/Test.php
