language: php
php:
  - 5.5.9
  - 5.3.3
  - 5.4
  - 5.5

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  ##PHPUnit
  - chmod +x phpUtils/phpunit
  - export PATH=$PATH:phpUtils
  
before_script: 
  - java -jar phpUtils/selenium-server.jar &
  - sleep 20
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  ## PHPLOC
  - pear install phpunit/phploc
  - phpenv rehash
  ##php-cs-fixer
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - chmod +x php-cs-fixer.phar

script:
  - cd app
  - php php-cs-fixer.phar fix .
  - phpcs --standard=Zend *.php
  - phploc Usuario.php
  - phploc functions.php
  - phploc index.php
  - phploc bienvenido.php
  - phploc crearcuenta.php

  - cd test
  ##Test.php
  - php-cs-fixer.phar fix Test.php
  - phpcs --standard=Zend Test.php
  - phploc Test.php
  - phpunit Test.php
  - cd ..
  - phpunit --coverage-html . Test.php
 
 
  
